# Simple Data Provider

### General
debug: false 
server:
   port: 9021

security:
  basic:
    enabled: false
  user:
      name: client
      password: password
      
# Info
info:
   app:
      name: ${spring.application.name}
      description: haf-tech Service
 

config:
  # Supported backend systems: IEX, FMP
  stock.backend.id: FMP
  
# ### Logging
logging.level:
  com.haddouti.springeco.samples.provider: DEBUG  
  
   