# Simple Data Provider

### General
debug: false 
server:
   port: 9041

security:
  basic:
    enabled: false
  user:
      name: client
      password: password
      
# Info
info:
   app:
      name: ${spring.application.name}
      description: haf-tech Service
 

config:
  # Supported backend systems: IEX, FMP
  stock.backend.id: FMP
  
# ### Logging
logging.level:
  com.haddouti.springeco.samples.provider: DEBUG  
  
   
# ### Profiles
---
# stock-fmp
# Stock Backend: FMP
 
spring:
   profiles: stock-fmp

server:
   port: 9042
   
config:
  # Supported backend systems: IEX, FMP
  stock.backend.id: FMP
  
---
# stock-fmp
# Stock Backend: IEX
 
spring:
   profiles: stock-iex

server:
   port: 9043
   
config:
  # Supported backend systems: IEX, FMP
  stock.backend.id: IEX
  
---
# default-port
# Relevant for docker usage (convention over configuration - cloud provider expects this port for default routing)
 
spring:
   profiles: default-port

server:
   port: 8080  
    