# Service Registry
# application.yml

# ### General
server:
   port: 9876
   
spring:
  security:
    user:
      name: user
      password: password    
         
# Info
info:
   app:
      name: ${spring.application.name}
      description: haf-tech Service Registry         
         
# ### Eureka
# Do not self-register    
eureka:
  client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://user:password@${eureka.instance.hostname}:${server.port}/eureka/
  instance:
      leaseRenewalIntervalInSeconds: 10
  healthcheck:
    enabled: true      

# Logging
logging:
    level:
       com.netflix.eureka: 'OFF'
       com.netflix.discovery: 'OFF'
       