# Service 1
# application.yml

# ### General
debug: true
server:
   port: 9021


spring:
# Deactivated in Spring Boot 2.x
#  security:
#    basic:
#      enabled: false
  security:
    user:
      name: user
      password: password       
      
#No auth  protected 
endpoints:
   shutdown:
      sensitive: false
      #Enable shutdown endpoint
      enabled: true
      
# Activate all management endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
# Info
info:
   app:
      name: ${spring.application.name}
      description: Haftech Service

config:
  # deactivate security
  security:
      enabled: false      
   
# ### Eureka
eureka:
   client:
      # Retrieve registry info from Eureka and cache the
      fetchRegistry: true
      # Update cached registry info. Default 30sec
      registryFetchIntervalSeconds: 5
      registerWithEureka: true
      serviceUrl:
        defaultZone: http://user:password@localhost:9876/eureka/
      # Activate health check to Eureka Server  
      healthcheck:
         enabled: true
   instance:
      # Renew interval (heartbeat) to Eureka Server. Default is 30sec
      leaseRenewalIntervalInSeconds: 10
      statusPageUrlPath: /actuator/info
      healthCheckUrlPath: /actuator/health
   metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      env: ${spring.profiles.active}
      blub: 'ABC'   

